import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

class ReportPdfService {
  Future<Uint8List> generateReport({
    required String title,
    required String workspaceName,
    required String generatedBy,
    required List<KpiData> kpis,
    required String aiSummary,
    required List<TableData> tables,
  }) async {
    final pdf = pw.Document();
    final dateStr = DateFormat('MMMM d, yyyy').format(DateTime.now());
    final primaryColor = PdfColor.fromHex('#6366F1');

    // Cover page
    pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(0),
      build: (context) => pw.Stack(
        children: [
          pw.Container(
            width: double.infinity,
            height: double.infinity,
            color: primaryColor,
          ),
          pw.Positioned(
            top: 200,
            left: 60,
            right: 60,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('InsightBoard',
                  style: pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 16,
                    fontWeight: pw.FontWeight.normal,
                    letterSpacing: 3,
                  ),
                ),
                pw.SizedBox(height: 20),
                pw.Text(title,
                  style: pw.TextStyle(
                    color: PdfColors.white,
                    fontSize: 36,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 16),
                pw.Divider(color: PdfColors.white, thickness: 2),
                pw.SizedBox(height: 16),
                pw.Text('Workspace: $workspaceName',
                  style: const pw.TextStyle(color: PdfColors.white, fontSize: 14),
                ),
                pw.SizedBox(height: 8),
                pw.Text('Generated by: $generatedBy',
                  style: const pw.TextStyle(color: PdfColors.white, fontSize: 14),
                ),
                pw.SizedBox(height: 8),
                pw.Text('Date: $dateStr',
                  style: const pw.TextStyle(color: PdfColors.white, fontSize: 14),
                ),
              ],
            ),
          ),
        ],
      ),
    ));

    // KPI Summary page
    if (kpis.isNotEmpty) {
      pdf.addPage(pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _sectionTitle('Key Performance Indicators', primaryColor),
            pw.SizedBox(height: 20),
            pw.Wrap(
              spacing: 16,
              runSpacing: 16,
              children: kpis.map((kpi) => _kpiBox(kpi, primaryColor)).toList(),
            ),
          ],
        ),
      ));
    }

    // AI Summary page
    if (aiSummary.isNotEmpty) {
      pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          _sectionTitle('AI Analysis Report', primaryColor),
          pw.SizedBox(height: 20),
          ..._parseMarkdown(aiSummary),
        ],
      ));
    }

    // Data tables
    for (final table in tables) {
      pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          _sectionTitle(table.title, primaryColor),
          pw.SizedBox(height: 16),
          pw.TableHelper.fromTextArray(
            headers: table.headers,
            data: table.rows.take(50).toList(),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
              fontSize: 9,
            ),
            headerDecoration: pw.BoxDecoration(color: primaryColor),
            cellStyle: const pw.TextStyle(fontSize: 8),
            cellPadding: const pw.EdgeInsets.all(6),
            cellAlignments: {
              for (int i = 0; i < table.headers.length; i++)
                i: pw.Alignment.centerLeft,
            },
            border: pw.TableBorder.all(color: PdfColors.grey300),
            oddRowDecoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#F8FAFC'),
            ),
          ),
          if (table.rows.length > 50)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 8),
              child: pw.Text(
                'Showing 50 of ${table.rows.length} rows',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
              ),
            ),
        ],
      ));
    }

    // Footer page
    pdf.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Center(
        child: pw.Column(
          mainAxisAlignment: pw.MainAxisAlignment.center,
          children: [
            pw.Text('End of Report',
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold,
                  color: primaryColor),
            ),
            pw.SizedBox(height: 16),
            pw.Text('Generated by InsightBoard AI',
              style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey600),
            ),
            pw.SizedBox(height: 8),
            pw.Text(dateStr,
              style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey500),
            ),
          ],
        ),
      ),
    ));

    return pdf.save();
  }

  pw.Widget _sectionTitle(String text, PdfColor color) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(text, style: pw.TextStyle(
          fontSize: 22, fontWeight: pw.FontWeight.bold, color: color,
        )),
        pw.SizedBox(height: 4),
        pw.Container(width: 60, height: 3, color: color),
      ],
    );
  }

  pw.Widget _kpiBox(KpiData kpi, PdfColor color) {
    return pw.Container(
      width: 220,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(kpi.title, style: const pw.TextStyle(
            fontSize: 11, color: PdfColors.grey700,
          )),
          pw.SizedBox(height: 8),
          pw.Text(kpi.value, style: pw.TextStyle(
            fontSize: 22, fontWeight: pw.FontWeight.bold, color: color,
          )),
          if (kpi.change != null) ...[
            pw.SizedBox(height: 4),
            pw.Text(kpi.change!,
              style: pw.TextStyle(
                fontSize: 10,
                color: kpi.isPositive ? PdfColors.green : PdfColors.red,
              ),
            ),
          ],
        ],
      ),
    );
  }

  List<pw.Widget> _parseMarkdown(String text) {
    final widgets = <pw.Widget>[];
    final lines = text.split('\n');

    for (final line in lines) {
      if (line.trim().isEmpty) {
        widgets.add(pw.SizedBox(height: 8));
        continue;
      }
      if (line.startsWith('## ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(top: 16, bottom: 4),
          child: pw.Text(line.substring(3), style: pw.TextStyle(
            fontSize: 16, fontWeight: pw.FontWeight.bold,
          )),
        ));
      } else if (line.startsWith('### ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(top: 12, bottom: 4),
          child: pw.Text(line.substring(4), style: pw.TextStyle(
            fontSize: 13, fontWeight: pw.FontWeight.bold,
          )),
        ));
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(left: 16, bottom: 2),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('• ', style: const pw.TextStyle(fontSize: 11)),
              pw.Expanded(child: pw.Text(line.substring(2),
                style: const pw.TextStyle(fontSize: 11))),
            ],
          ),
        ));
      } else if (RegExp(r'^\d+\.\s').hasMatch(line)) {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(left: 16, bottom: 2),
          child: pw.Text(line, style: const pw.TextStyle(fontSize: 11)),
        ));
      } else {
        widgets.add(pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 4),
          child: pw.Text(
            line.replaceAll(RegExp(r'\*\*(.*?)\*\*'), r'\1'),
            style: const pw.TextStyle(fontSize: 11, lineSpacing: 1.5),
          ),
        ));
      }
    }
    return widgets;
  }
}

class KpiData {
  final String title;
  final String value;
  final String? change;
  final bool isPositive;
  KpiData({required this.title, required this.value, this.change, this.isPositive = true});
}

class TableData {
  final String title;
  final List<String> headers;
  final List<List<String>> rows;
  TableData({required this.title, required this.headers, required this.rows});
}
